server:
  port: 8080
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    image:
      path: /v1/images/**
    location:
      path: /v1/locations/**
    member:
      path: /v1/members/**
    notification:
      path: /v1/notifications/**
    order:
      path: /v1/orders/**
    payment:
      path: /v1/payments/**
    review:
      path: /v1/reviews/**
    store:
      path: /v1/store/**