spring:
  application:
    name: image
server:
  port: 809${SEQUENCE_NO}
eureka:
  instance:
    instance-id: ${spring.application.name}-${SEQUENCE_NO}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/